#!/usr/bin/env python3
"""Extract World Settings parameter metadata from main.slint.

Walks `crates/arksa-gui/ui/main.slint`, identifies each
`if root.current-category == N || ...: Rectangle` opener for N in 0..15, and
pulls the (group-title-or-empty, label, description-en, description-ja)
quadruple out of every WorldFloatRow / WorldBoolRow inside it.

Output is a Rust source file with a single
`PARAM_METADATA: &[(u32, &str, &str, &str, &str)]` const used at runtime
by the search-mode "hide categories / GroupBoxes with no matches" logic
so visible matches stack tightly without empty wrappers.

Usage:
    python3 tools/extract_param_metadata.py
        > crates/arksa-gui/src/world_param_metadata.rs

Categories 16 (Launch flags) and 17 (Mods) are skipped on purpose — both
use free-form text editors and aren't part of the row-level search.
"""

from __future__ import annotations
import re
import sys
from pathlib import Path

SLINT_PATH = Path(__file__).resolve().parent.parent / 'crates' / 'arksa-gui' / 'ui' / 'main.slint'

CAT_OPENER = re.compile(
    r'if root\.current-category == (\d+)'
    r'(?:\s*\|\|\s*(?:\(\s*)?root\.current-category == 99)?'
)

# Tokens we walk over inside a single category chunk to track which
# GroupBox (if any) contains each row. GroupBox openers and the brace of
# rows themselves are consumed by the group / row alternatives, so plain
# obrace / cbrace only matches stray `{` / `}` (e.g. inside VerticalBox).
TOKEN = re.compile(
    r'(?P<group>GroupBox\s*\{\s*title:\s*"(?P<title>[^"]+)")'
    r'|(?P<row>World(?:Float|Bool)Row\s*\{\s*'
    r'label:\s*"(?P<label>[^"]+)";'
    r'(?:\s*description:\s*root\.lang-ja\s*\?\s*"(?P<ja>[^"]*)"\s*:\s*"(?P<en>[^"]*)";)?'
    r'\s*(?:value\s*<=>|checked\s*<=>))'
    r'|(?P<obrace>\{)'
    r'|(?P<cbrace>\})',
    re.DOTALL,
)


def main() -> int:
    src = SLINT_PATH.read_text(encoding='utf-8')

    # Locate cat 0..15 openers (those have searchable rows). Cat 16 (Launch
    # flags) and 17 (Mods) use free-form text and are excluded.
    openers: list[tuple[int, int]] = []
    for m in CAT_OPENER.finditer(src):
        cat = int(m.group(1))
        if cat < 16:
            openers.append((cat, m.start()))
    openers.append((-1, len(src)))

    rows: list[tuple[int, str, str, str, str]] = []
    for i in range(len(openers) - 1):
        cat, start = openers[i]
        end = openers[i + 1][1]
        chunk = src[start:end]

        # Walk tokens to track GroupBox nesting context for each row.
        depth = 0
        group_stack: list[tuple[int, str]] = []  # (depth_at_open, title)
        for m in TOKEN.finditer(chunk):
            if m.group('group'):
                group_stack.append((depth, m.group('title')))
                depth += 1  # the `{` is part of the group token
            elif m.group('row'):
                label = m.group('label')
                en = m.group('en') or ''
                ja = m.group('ja') or ''
                group = group_stack[-1][1] if group_stack else ''
                rows.append((cat, group, label, en, ja))
                depth += 1  # the row's `{`
            elif m.group('obrace'):
                depth += 1
            elif m.group('cbrace'):
                depth -= 1
                if group_stack and group_stack[-1][0] == depth:
                    group_stack.pop()

    print(f'// {len(rows)} entries extracted from main.slint')
    print('//! Auto-generated by tools/extract_param_metadata.py — do not edit by hand.')
    print('//!')
    print('//! `(category, group-title-or-empty, label, description-en, description-ja)`')
    print('//! tuples used by the World Settings dialog\'s search to decide whether')
    print('//! a category Rectangle or GroupBox should be hidden in the cross-')
    print('//! category "🔍 Search results" view (cat == 99). When no row in a')
    print('//! category / group matches the current query, the corresponding')
    print('//! container is hidden so visible matches stack tightly without empty')
    print('//! wrappers.')
    print()
    print('pub const PARAM_METADATA: &[(u32, &str, &str, &str, &str)] = &[')
    for cat, group, label, en, ja in rows:
        en_esc = en.replace('\\', '\\\\').replace('"', '\\"')
        ja_esc = ja.replace('\\', '\\\\').replace('"', '\\"')
        group_esc = group.replace('\\', '\\\\').replace('"', '\\"')
        print(f'    ({cat}, "{group_esc}", "{label}", "{en_esc}", "{ja_esc}"),')
    print('];')

    return 0


if __name__ == '__main__':
    sys.exit(main())
