#!/usr/bin/env python3
"""Extract World Settings parameter metadata from main.slint.

Walks `crates/arksa-gui/ui/main.slint`, identifies each
`if root.current-category == N || root.current-category == 99: Rectangle`
opener for N in 0..15, and pulls the (label, description-en, description-ja)
triple out of every WorldFloatRow / WorldBoolRow inside it.

Output is a Rust source file with a single
`PARAM_METADATA: &[(u32, &str, &str, &str)]` const used at runtime by the
search-mode "hide categories with no matches" logic so that visible
matches stack tightly without empty-category gaps.

Usage:
    python3 tools/extract_param_metadata.py
        > crates/arksa-gui/src/world_param_metadata.rs

Categories 16 (Launch flags) and 17 (Mods) are skipped on purpose — both
use free-form text editors and aren't part of the row-level search.
"""

from __future__ import annotations
import re
import sys
from pathlib import Path

SLINT_PATH = Path(__file__).resolve().parent.parent / 'crates' / 'arksa-gui' / 'ui' / 'main.slint'

CAT_OPENER = re.compile(
    r'if root\.current-category == (\d+)'
    r'(?:\s*\|\|\s*root\.current-category == 99)?'
    r'\s*:\s*Rectangle'
)

ROW = re.compile(
    r'World(?:Float|Bool)Row\s*\{\s*'
    r'label:\s*"([^"]+)";'
    r'(?:\s*description:\s*root\.lang-ja\s*\?\s*"([^"]*)"\s*:\s*"([^"]*)";)?'
    r'\s*(?:value\s*<=>|checked\s*<=>)',
    re.DOTALL,
)


def main() -> int:
    src = SLINT_PATH.read_text(encoding='utf-8')

    openers: list[tuple[int, int]] = []
    for m in CAT_OPENER.finditer(src):
        cat = int(m.group(1))
        if cat < 16:
            openers.append((cat, m.start()))
    openers.append((-1, len(src)))

    rows: list[tuple[int, str, str, str]] = []
    for i in range(len(openers) - 1):
        cat, start = openers[i]
        end = openers[i + 1][1]
        chunk = src[start:end]
        for m in ROW.finditer(chunk):
            label = m.group(1)
            ja = m.group(2) or ''
            en = m.group(3) or ''
            rows.append((cat, label, en, ja))

    print(f'// {len(rows)} entries extracted from main.slint')
    print('//! Auto-generated by tools/extract_param_metadata.py — do not edit by hand.')
    print('//!')
    print('//! Compact `(category, label, description-en, description-ja)` tuples')
    print('//! used by the World Settings dialog\'s search to decide whether a')
    print('//! whole category should be hidden in the cross-category "🔍 Search')
    print('//! results" view (cat == 99). When no row in a category matches the')
    print('//! current query, the category Rectangle is hidden entirely so the')
    print('//! visible matches stack tightly without empty-category gaps.')
    print()
    print('pub const PARAM_METADATA: &[(u32, &str, &str, &str)] = &[')
    for cat, label, en, ja in rows:
        en_esc = en.replace('\\', '\\\\').replace('"', '\\"')
        ja_esc = ja.replace('\\', '\\\\').replace('"', '\\"')
        print(f'    ({cat}, "{label}", "{en_esc}", "{ja_esc}"),')
    print('];')

    return 0


if __name__ == '__main__':
    sys.exit(main())
